@startuml ErrorDiagram
!pragma useVerticalIf on
start
:Create a Deposit;
if (http_code == 2XX?) then (no)
 :Move to Fail;
 stop
 elseif (Did we get redirect URL?) then (yes);
  :Go to the next step;
  stop
 else (no)
:Move to Fail and send msg to sentry;
stop
@enduml